### ISSUE TITLE
Syntax error?

### ISSUE THREAD

**Issue by fluidscroll** [nachocinalli/adapt-lenisSmoothScrolling#1]
Hi,

 I've successfully installed your plugin into the Adapt Authoring tool, but when I build a course a get the below error message. (I'm not a developer, I have basic coding skills).

Command failed: grunt server-build:prod --outputdir=courses/65b8fb3d57bc06000a948d1e/661e9322f8b58e709961a0c9/build --theme=65b8fd4f57bc06000a948d39 --menu=adapt-contrib-boxMenu

Fatal error: Error: Parse error using esprima for file: /adapt_authoring/temp/65b8fb3d57bc06000a948d1e/adapt_framework/src/extensions/adapt-lenisSmoothScrolling/js/adapt-lenisSmoothScrolling.js
Error: Line 1: Unexpected token
In module tree:
    core/js/app

Any suggestions? Thank you in advance.

**Comment by nachocinalli** [comment]
Hi @fluidscroll , I cannot reproduce the error when testing it on my local  Adapt Authoring Tool (AAT). Please ensure the extension has been uploaded correctly in your AAT. Check that the libraries folder and all the files that are part of this extension are present. Sometimes, AAT fails to import and does not copy all the files (this could be the case). Additionally, could you please let me know which version of the Adapt Framework you are using?

**Comment by fluidscroll** [comment]
Hi @nachocinalli,

Thank you for your quick response. I will double check the libraries folder. I'm using version 5.7.0 

Thanks

**Comment by nachocinalli** [comment]
Ah, no, it's because of the version of the Adapt framework you are using. The extension uses a module bundler that was implemented in v5.8.0. If you don't plan to update the version of Adapt, this extension is very easy to modify to work in v5.7.0

**Comment by nachocinalli** [comment]
@fluidscroll please uninstall and reinstall the extension from [compat-v5.7.0](https://github.com/nachocinalli/adapt-lenisSmoothScrolling/archive/refs/tags/v0.9.2.zip). Then test again on your AAT.

**Comment by fluidscroll** [comment]
Hi @nachocinalli, it works now! Thanks so much, it looks great.

Thank you!
